version: "3"
services:
  redisd:
    image: "redis:6.2.4-alpine"
    ports:
      - "6379:6379"
    networks:
      - mariadb_database-net
    volumes:
      - ./data:/var/lib/redis/data
networks:
  mariadb_database-net:
    external: true
