version: "3"
services:
  db:
    image: "postgres:13.3-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: taufik
      POSTGRES_DB: postgres
    networks:
      - "database-net"
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: "adminer"
    ports:
      - "8080:8080"
    networks:
      - "database-net"

networks:
  database-net:
