version: "3.9"
services: 
  db:
    build: .
    ports: 
      - "3306:3306"
    networks:
      - "myshop"
    volumes: 
      - database:/var/lib/mariadb/data
    command: ['--default-storage-engine=RocksDB', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  adminer:
    image: adminer
    ports:
      - 3000:8080
    networks:
      - "myshop"

networks:
  myshop:
    external: true

volumes:
  database: