version: "3.9"
services: 
  db:
    build: .
    ports: 
      - "3306:3306"
    networks:
      - "database-net"
    volumes: 
      - database-vol:/var/lib/mariadb/data

  adminer:
    image: adminer
    ports:
      - 3000:8080
    networks:
      - "database-net"

networks:
  database-net:
    driver: overlay

volumes:
  database-vol: